### ISSUE TITLE
Code บรรทัดนี้รันแล้ว error ครับ

### ISSUE THREAD

**Issue by teerasej** [teerasej/blockchain-beginner#1]
## โค้ดที่มีปัญหา

`geth --rinkeby`

**Comment by ChannaphatTaweesuksirianan** [comment]
ใช่ผม ก็เจอครับ ยังแก้ไม่ได้เลย

**Comment by bie-test** [comment]
#error เหมือนกันเลยย

**Comment by teerasej** [comment]
@bie-test ขอข้อมูลด้วยฮะ พวก Screen shot หรือ error log

**Comment by teerasej** [comment]
แก้แล้วครับ ลองดูใหม่

**Comment by ChannaphatTaweesuksirianan** [comment]
ยัง ขึ้น error อยู่ครับ
